AspnetCoreIdentityApp.Web/Areas/Admin/Models/UserViewModel.cs
namespace AspnetCoreIdentityApp.Web.Areas.Admin.Models
{
    public class UserViewModel
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
    }
}

AspnetCoreIdentityApp.Web/Models/AppDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AspnetCoreIdentityApp.Web.Models
{
    public class AppDbContext:IdentityDbContext<AppUser,AppRole,string>//string random guid değerler oluşturacak kullanıcılar oluşturulurken
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }



    }
}

AspnetCoreIdentityApp.Web/Models/AppRole.cs
using Microsoft.AspNetCore.Identity;

namespace AspnetCoreIdentityApp.Web.Models
{
    public class AppRole:IdentityRole
    {
    }
}

AspnetCoreIdentityApp.Web/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace AspnetCoreIdentityApp.Web.Models
{
    public class AppUser:IdentityUser
    {
        public string? City { get; set; }
    }
}

AspnetCoreIdentityApp.Web/Models/ErrorViewModel.cs
namespace AspnetCoreIdentityApp.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspnetCoreIdentityApp.Web/ViewModels/SignInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspnetCoreIdentityApp.Web.ViewModels
{
    public class SignInViewModel
    {
        [EmailAddress(ErrorMessage = "Email formatı yanlıştır.")]
        [Required(ErrorMessage = "Email alanı boş bırakılamaz.")]
        [Display(Name = "Email:")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "Şifre alanı boş bırakılamaz.")]
        [Display(Name = "Şifre:")]
        public string? Password { get; set; }
        [Display(Name = "Beni Hatırla:")]
        public bool RememberMe { get; set; }
    }
}

AspnetCoreIdentityApp.Web/ViewModels/SignUpViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspnetCoreIdentityApp.Web.ViewModels
{
    public class SignUpViewModel
    {
        [Required(ErrorMessage ="Kullanıcı Adı alanı boş bırakılamaz.")]
        [Display(Name ="Kullanıcı Adı:")]
        public string? UserName { get; set; }

        [EmailAddress(ErrorMessage ="Email formatı yanlıştır.")]
        [Required(ErrorMessage = "Email alanı boş bırakılamaz.")]
        [Display(Name = "Email:")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Telefon alanı boş bırakılamaz.")]
        [Display(Name = "Telefon:")]
        public string? Phone { get; set; }

        [Required(ErrorMessage = "Şifre alanı boş bırakılamaz.")]
        [Display(Name = "Şifre:")]
        public string? Password { get; set; }

        [Compare(nameof(Password),ErrorMessage ="Şifreler uyuşmuyor.")]
        [Required(ErrorMessage = "Şifre Tekrar alanı boş bırakılamaz.")]
        [Display(Name = "Şifre Tekrar:")]
        public string? PasswordConfirm { get; set; }

    }
}

AspnetCoreIdentityApp.Web/Areas/Admin/Controllers/HomeController.cs
using AspnetCoreIdentityApp.Web.Areas.Admin.Models;
using AspnetCoreIdentityApp.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspnetCoreIdentityApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public HomeController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UserList()
        {
            var userList = await _userManager.Users.ToListAsync();
            var userViewModelList = userList.Select(x=>new UserViewModel()
            {
                Id = x.Id,
                Email=x.Email,
                Name=x.UserName
            }).ToList();

            return View(userViewModelList);
        }
    }
}

AspnetCoreIdentityApp.Web/Controllers/HomeController.cs
using AspnetCoreIdentityApp.Web.Extensions;
using AspnetCoreIdentityApp.Web.Models;
using AspnetCoreIdentityApp.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspnetCoreIdentityApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public HomeController(ILogger<HomeController> logger, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _logger = logger;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel request)
        {
            if (!ModelState.IsValid) return View();


            var identityResult=await _userManager.CreateAsync(new() { UserName=request.UserName,PhoneNumber=request.Phone,Email=request.Email},request.PasswordConfirm);
            if (identityResult.Succeeded)
            {
                TempData["SuccessMessage"] = "Üyelik kayıt işlemi başarıyla gerçekleşmiştir.";

                //return RedirectToAction("SignUp"); 
                return RedirectToAction(nameof(HomeController.SignUp));
            }

            //foreach (IdentityError item in identityResult.Errors)
            //{
            //    ModelState.AddModelError(string.Empty,item.Description);
            //}
            ModelState.AddModelErrorList(identityResult.Errors.Select(x=>x.Description).ToList());

            return View();
        }

        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(SignInViewModel request,string? returnUrl=null)
        {
            if (!ModelState.IsValid) return View();

            returnUrl = returnUrl ?? Url.Action("Index","Home");//eğer nullsa yap değilse kendi değeri atanacak

            var hasUser = await _userManager.FindByEmailAsync(request.Email);

            if (hasUser==null)
            {
                ModelState.AddModelError(string.Empty, "Email veya şifre yanlış");
                return View();
            }

            var signInResult = await _signInManager.PasswordSignInAsync(hasUser,request.Password,request.RememberMe,true);

            if (signInResult.Succeeded)
            {
                return Redirect(returnUrl);
            }

            if (signInResult.IsLockedOut)
            {
                ModelState.AddModelError(string.Empty, "Çok fazla hatalı giriş yapıldığı için 4 dakika boyunca giriş yapamazsınız.");
                return View();
            }

            ModelState.AddModelErrorList(new List<string>() { $"Email veya şifre yanlış", $"(Başarısız giriş sayısı: {await _userManager.GetAccessFailedCountAsync(hasUser)})" });


            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspnetCoreIdentityApp.Web/Controllers/MemberController.cs
using AspnetCoreIdentityApp.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AspnetCoreIdentityApp.Web.Controllers
{
    public class MemberController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;

        public MemberController(SignInManager<AppUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task Logout()
        {
            await _signInManager.SignOutAsync();

            //return RedirectToAction("Index", "Home");
        }
    }
}

AspnetCoreIdentityApp.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Admin Paneline hoş geldiniz.</h1>

AspnetCoreIdentityApp.Web/Areas/Admin/Views/Home/UserList.cshtml
@{
    ViewData["Title"] = "UserList";
}
@model List<UserViewModel>

<h1>Üye Listesi</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kullanıcı Adı</th>
            <th>Email</th>
            <th>Roller</th>
            <th>Rol İşlemleri</th>
        </tr>
    </thead>


    <tbody>


        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>
                  @*<user-role-names user-id="@item.Id"></user-role-names>*@
                </td>
                <td>
                    @*<a asp-controller="Roles" asp-action="AssignRoleToUser" asp-route-id="@item.Id">Rol ata</a>*@
                </td>
            </tr>
        }







    </tbody>
</table>

AspnetCoreIdentityApp.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspnetCoreIdentityApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspnetCoreIdentityApp.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspnetCoreIdentityApp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="UserList">Üye Listesi</a>
                        </li>

                           <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspnetCoreIdentityApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspnetCoreIdentityApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspnetCoreIdentityApp.Web/Views/Home/SignIn.cshtml
@{
    ViewData["Title"] = "SignIn";

}
@model SignInViewModel

@section Scripts
    {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Kullanıcı Girişi </h2>

        <div asp-validation-summary=ModelOnly class="alert alert-danger" role="alert">
        </div>
        @*<form asp-controller="Home" asp-action="SignIn" asp-route-returnUrl="@Context.Request.Query["returnURl"]" method="post">*@
        <form asp-controller="Home" asp-action="SignIn" method="post">
            <div class="mb-3">
                <label for="Email" class="form-label" asp-for="Email"></label>
                <input  class="form-control" asp-for="Email">
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>
            <div class="mb-3">
                <label for="Password" class="form-label" asp-for="Password"></label>
                <input type="password" class="form-control" asp-for="Password">
            </div>

            <div class="row">
                <div class="col-md-6">

                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" asp-for="RememberMe">
                        <label class="form-check-label" for="RememberMe" asp-for="RememberMe"></label>
                    </div>

                </div>
                <div class="col-md-6 ">
                    <a  class="btn btn-outline-secondary btn-sm float-end" asp-controller="Home" asp-action="ForgetPassword">Şifremi unuttum</a>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Giriş Yap</button>
            <div>
            </div>


        </form>
    </div>
</div>

AspnetCoreIdentityApp.Web/Views/Home/SignUp.cshtml
@{
    ViewData["Title"] = "SignUp";
}


@model SignUpViewModel

@section Scripts
{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Kullanıcı Kayıt</h2>

        @if (TempData["SuccessMessage"]!=null)
        {
            <div class="alert alert-info" role="alert">
              @TempData["SuccessMessage"]
            </div>
        }

         <div asp-validation-summary=ModelOnly class="alert alert-danger" role="alert">
           
        </div>

        <form asp-controller="Home" asp-action="SignUp" method="post">
            <div class="row mb-3">
                <label for="UserName" class="col-md-4 col-form-label" asp-for="UserName"></label>
                <div class="col-md-8 ">
                    <input asp-for="UserName" class="form-control">
                    <span class="text-danger" asp-validation-for="UserName"></span>
                </div>
            </div>


            <div class="row mb-3">
                <label for="Email" class="col-md-4 col-form-label" asp-for="Email"></label>
                <div class="col-md-8">
                    <input asp-for="Email" class="form-control">
                    <span class="text-danger" asp-validation-for="Email"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="Phone" class="col-md-4 col-form-label" asp-for="Phone"></label>
                <div class="col-md-8">
                    <input asp-for="Phone" class="form-control">
                    <span class="text-danger" asp-validation-for="Phone"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label for="Password" class="col-md-4 col-form-label" asp-for="Password"></label>
                <div class="col-md-8">
                    
                    <input asp-for="Password" class="form-control">
                    <span class="text-danger" asp-validation-for="Password"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label for="PasswordConfirm" class="col-md-4 col-form-label" asp-for="PasswordConfirm"></label>
                <div class="col-md-8">
                    <input asp-for="PasswordConfirm" class="form-control">
                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>
                </div>
            </div>


            <div class="row mb-3">
               
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn btn-primary">Kayıt Ol</button>
                </div>
            </div>


          
        </form>
    </div>
</div>

AspnetCoreIdentityApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspnetCoreIdentityApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspnetCoreIdentityApp.Web.styles.css" asp-append-version="true" />

    @await RenderSectionAsync("Css", required: false)
</head>
<body>
    <header>
         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreIdentityApp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="AnkaraPage">Ankara Sayfa</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="ExchangePage">Borsa Sayfa</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="ViolencePage">Şiddet Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order Sayfa(Permission)</a>
                        </li>
                    </ul>

               <partial name="_Navbarlogin" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspnetCoreIdentityApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspnetCoreIdentityApp.Web/Views/Shared/_NavbarLogin.cshtml
@{
    ViewData["Title"] = "_NavbarLogin";
}




<ul class="navbar-nav me-0">
    @if (User.Identity!.IsAuthenticated)//runtime da ? ! vs. hiçbir önemi yok compiler için sadece
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @User.Identity.Name
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-route-returnurl="/Home/Index" asp-controller="Member" asp-action="Logout">Çıkış yap</a></li>

            </ul>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark mx-1" asp-area="" asp-controller="Home" asp-action="SignUp">Kayıt Ol</a>
        </li>
            <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignIn">Giriş Yap</a>
        </li> 
    }
</ul>       